from typing import Any, Dict, List, Optional
from ..config import settings
from ..schemas.common import PredictionStatus
from ..schemas.prediction import (
    PredictionResponse,
    RecommendationResponse,
    TreatmentItem,
)
from ..services.inference_engine import ModelPrediction
from treatment_database.repository import TreatmentRepository


class TreatmentService:
    """
    Coordinates disease lookup, health score computation, Integrated Pest Management (IPM)
    recommendation assembly, and agricultural safety disclaimers.
    """

    def __init__(self, repository: Optional[TreatmentRepository] = None):
        self.repository = repository or TreatmentRepository(settings.TREATMENT_DB_DIR)

    def calculate_health_score(self, base_score: int, confidence: float, is_healthy: bool) -> int:
        """
        Calculates a dynamic 0-100 Plant Health Score based on disease baseline and confidence.
        """
        if is_healthy:
            # Healthy plants range between 90 and 100
            score = int(88 + (confidence * 10))
            return min(100, max(85, score))

        # For diseased plants: confidence indicates certainty of disease presence
        # Higher confidence in a severe disease reduces health score slightly towards true baseline
        modulated = int(base_score - (confidence - 0.5) * 10)
        return min(80, max(10, modulated))

    def build_prediction_response(
        self,
        prediction: ModelPrediction,
        inference_time_ms: float = 0.0,
        forced_status: Optional[PredictionStatus] = None,
    ) -> PredictionResponse:
        """
        Constructs the complete, user-facing PredictionResponse payload.
        Handles normal predictions, uncertain detections, unsupported crops, and unknown classes.
        """
        disclaimers = self.repository.disclaimers
        general_disclaimer = disclaimers.get(
            "general_disclaimer",
            "This advisory is generated by PlantScan AI for preliminary screening. Consult local extension agronomists before field treatments.",
        )
        chemical_safety = disclaimers.get("chemical_safety_warning", "")
        uncertainty_notice = disclaimers.get("uncertainty_notice", "")

        # 1. Handle Unsupported Crop Scenario
        if prediction.predicted_class == "unsupported_crop":
            unknown_info = self.repository.default_unknown
            recommendation = RecommendationResponse(
                summary=f"The provided crop '{prediction.crop}' is currently not in the PlantScan AI supported crop database.",
                organic=[],
                chemical=[],
                prevention=[
                    "Please submit images of supported crops (e.g., Tomato, Potato, Rice, Banana, Cotton, Mango).",
                    "Contact local agricultural extension services for diagnostics on unsupported crop species.",
                ],
                safety_notes=[
                    "Do not apply synthetic pesticides without certified confirmation of the target plant pathogen."
                ],
                photo_guidance=unknown_info.get("photo_guidance", []),
                disclaimer=general_disclaimer,
                sources=unknown_info.get("sources", []),
            )
            return PredictionResponse(
                status=PredictionStatus.UNSUPPORTED_CROP,
                crop=prediction.crop,
                predicted_class="unsupported_crop",
                display_name=f"Unsupported Crop ({prediction.crop})",
                confidence=prediction.confidence,
                is_healthy=False,
                plant_part=prediction.plant_part,
                plant_health_score=50,
                recommendation=recommendation,
                inference_time_ms=inference_time_ms,
                message=f"Crop '{prediction.crop}' is outside the current diagnostic scope.",
            )

        # 2. Handle Low Confidence / Uncertain / Unknown Scenario
        is_uncertain = prediction.confidence < settings.CONFIDENCE_THRESHOLD or forced_status == PredictionStatus.UNCERTAIN

        if is_uncertain or prediction.predicted_class == "unknown":
            unknown_info = self.repository.default_unknown
            organic_items = [
                TreatmentItem(
                    name=item["name"],
                    method=item.get("method"),
                    application=item.get("application"),
                    frequency=item.get("frequency"),
                    caution_level="Low",
                )
                for item in unknown_info.get("organic_measures", [])
            ]

            safety_notes = [uncertainty_notice] if uncertainty_notice else []
            if chemical_safety:
                safety_notes.append(chemical_safety)

            recommendation = RecommendationResponse(
                summary=(
                    f"Diagnostic confidence ({prediction.confidence*100:.1f}%) is below the {settings.CONFIDENCE_THRESHOLD*100:.0f}% threshold. "
                    "Visual symptoms are ambiguous. Do not apply chemical pesticides without physical verification."
                ),
                organic=organic_items,
                chemical=[],  # Never prescribe chemicals for uncertain diagnoses
                prevention=unknown_info.get("prevention_measures", []),
                safety_notes=safety_notes,
                photo_guidance=unknown_info.get("photo_guidance", []),
                disclaimer=general_disclaimer,
                sources=unknown_info.get("sources", []),
            )

            status = PredictionStatus.UNCERTAIN if is_uncertain else PredictionStatus.UNKNOWN

            return PredictionResponse(
                status=status,
                crop=prediction.crop,
                predicted_class=prediction.predicted_class,
                display_name=prediction.display_name or "Uncertain Diagnosis",
                confidence=prediction.confidence,
                is_healthy=prediction.is_healthy,
                plant_part=prediction.plant_part,
                plant_health_score=50,
                recommendation=recommendation,
                inference_time_ms=inference_time_ms,
                message="Low diagnostic certainty. Follow the photo tips to retake a clear photo in natural light.",
            )

        # 3. Handle Confirmed Known Disease / Healthy Prediction
        treatment_data = self.repository.get_by_class(prediction.predicted_class)
        if not treatment_data:
            treatment_data = self.repository.get_by_crop_and_disease(prediction.crop, prediction.predicted_class)

        if not treatment_data:
            # Fallback if class exists in model but missing detailed JSON
            treatment_data = {
                "display_name": prediction.display_name or prediction.predicted_class.replace("_", " ").title(),
                "base_health_score": 90 if prediction.is_healthy else 50,
                "symptoms": "Diagnostic record present.",
                "organic_measures": [],
                "chemical_measures": [],
                "prevention_measures": ["Maintain general good crop hygiene."],
                "sources": ["PlantScan AI Knowledge Base"],
            }

        base_health = treatment_data.get("base_health_score", 90 if prediction.is_healthy else 45)
        health_score = self.calculate_health_score(base_health, prediction.confidence, prediction.is_healthy)

        # Build Organic Treatment Items
        organic_items = [
            TreatmentItem(
                name=m["name"],
                method=m.get("method"),
                application=m.get("application"),
                frequency=m.get("frequency"),
                caution_level="Low",
            )
            for m in treatment_data.get("organic_measures", [])
        ]

        # Build Chemical Treatment Items
        chemical_items = [
            TreatmentItem(
                name=c["name"],
                active_ingredient=c.get("active_ingredient"),
                dosage=c.get("dosage"),
                safety_precautions=c.get("safety_precautions"),
                caution_level=c.get("caution_level", "Moderate"),
            )
            for c in treatment_data.get("chemical_measures", [])
        ]

        # Safety Notes
        safety_notes: List[str] = []
        if chemical_items and chemical_safety:
            safety_notes.append(chemical_safety)
        if disclaimers.get("organic_guidance_note"):
            safety_notes.append(disclaimers["organic_guidance_note"])

        summary_text = (
            f"Healthy plant detected with {prediction.confidence*100:.1f}% confidence."
            if prediction.is_healthy
            else f"Identified {treatment_data.get('display_name', prediction.display_name)} with {prediction.confidence*100:.1f}% confidence."
        )

        recommendation = RecommendationResponse(
            summary=summary_text,
            organic=organic_items,
            chemical=chemical_items,
            prevention=treatment_data.get("prevention_measures", []),
            safety_notes=safety_notes,
            disclaimer=general_disclaimer,
            sources=treatment_data.get("sources", []),
        )

        return PredictionResponse(
            status=PredictionStatus.SUCCESS,
            crop=treatment_data.get("crop", prediction.crop),
            predicted_class=prediction.predicted_class,
            display_name=treatment_data.get("display_name", prediction.display_name),
            confidence=prediction.confidence,
            is_healthy=prediction.is_healthy,
            plant_part=prediction.plant_part,
            plant_health_score=health_score,
            recommendation=recommendation,
            inference_time_ms=inference_time_ms,
            message="Diagnosis completed successfully.",
        )


_treatment_service_instance: Optional[TreatmentService] = None


def get_treatment_service() -> TreatmentService:
    global _treatment_service_instance
    if _treatment_service_instance is None:
        _treatment_service_instance = TreatmentService()
    return _treatment_service_instance
