from typing import Any, Dict, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from ..schemas.common import ErrorDetail
from ..schemas.prediction import RecommendationResponse, TreatmentItem
from ..services.treatment_service import TreatmentService, get_treatment_service

router = APIRouter(prefix="/treatments", tags=["Treatment Database"])


@router.get(
    "/crops",
    response_model=List[str],
    summary="List Supported Crops",
    description="Retrieve all agricultural crop species currently supported in the treatment knowledge base.",
)
async def list_crops(
    treatment_svc: TreatmentService = Depends(get_treatment_service),
) -> List[str]:
    return treatment_svc.repository.list_supported_crops()


@router.get(
    "/classes",
    response_model=List[str],
    summary="List Canonical Disease Classes",
    description="Retrieve all canonical disease and healthy class identifiers in the database.",
)
async def list_classes(
    treatment_svc: TreatmentService = Depends(get_treatment_service),
) -> List[str]:
    return treatment_svc.repository.list_all_canonical_classes()


@router.get(
    "/{crop}/{disease}",
    response_model=RecommendationResponse,
    summary="Query Treatment by Crop & Disease",
    description="Look up organic, chemical, and preventive treatment recommendations for a specific crop disease.",
    responses={404: {"model": ErrorDetail}},
)
async def get_treatment_by_disease(
    crop: str,
    disease: str,
    treatment_svc: TreatmentService = Depends(get_treatment_service),
) -> RecommendationResponse:
    record = treatment_svc.repository.get_by_crop_and_disease(crop, disease)
    if not record:
        record = treatment_svc.repository.get_by_class(disease)

    if not record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "status": "error",
                "error_code": "TREATMENT_NOT_FOUND",
                "message": f"No treatment advisory found for crop '{crop}' and disease '{disease}'.",
                "hint": "Check /treatments/classes or /treatments/crops for valid names.",
            },
        )

    disclaimers = treatment_svc.repository.disclaimers
    general_disclaimer = disclaimers.get(
        "general_disclaimer",
        "This advisory is generated by PlantScan AI. Always consult local agricultural extension services.",
    )
    chemical_safety = disclaimers.get("chemical_safety_warning", "")

    organic_items = [
        TreatmentItem(
            name=m["name"],
            method=m.get("method"),
            application=m.get("application"),
            frequency=m.get("frequency"),
            caution_level="Low",
        )
        for m in record.get("organic_measures", [])
    ]

    chemical_items = [
        TreatmentItem(
            name=c["name"],
            active_ingredient=c.get("active_ingredient"),
            dosage=c.get("dosage"),
            safety_precautions=c.get("safety_precautions"),
            caution_level=c.get("caution_level", "Moderate"),
        )
        for c in record.get("chemical_measures", [])
    ]

    safety_notes = []
    if chemical_items and chemical_safety:
        safety_notes.append(chemical_safety)
    if disclaimers.get("organic_guidance_note"):
        safety_notes.append(disclaimers["organic_guidance_note"])

    return RecommendationResponse(
        summary=f"Treatment protocol for {record.get('display_name', disease)} on {record.get('crop', crop)}.",
        organic=organic_items,
        chemical=chemical_items,
        prevention=record.get("prevention_measures", []),
        safety_notes=safety_notes,
        disclaimer=general_disclaimer,
        sources=record.get("sources", []),
    )
