import json
from pathlib import Path
from typing import Any, Dict, List, Optional


class TreatmentRepository:
    """
    Loads, indexes, and queries Integrated Pest Management (IPM) treatment advisories
    across all supported agricultural crop species.
    """

    def __init__(self, db_dir: Optional[Path] = None):
        self.db_dir = db_dir or Path(__file__).resolve().parent
        self.crop_records: Dict[str, Dict[str, Any]] = {}
        self.class_to_record: Dict[str, Dict[str, Any]] = {}
        self.disclaimers: Dict[str, str] = {}
        self.default_unknown: Dict[str, Any] = {}
        self.reload()

    def reload(self) -> None:
        self.crop_records.clear()
        self.class_to_record.clear()

        # Load crop JSON files
        json_files = list(self.db_dir.glob("*.json"))
        for json_file in json_files:
            if json_file.stem in {"disclaimers", "unknown_crop"}:
                continue

            try:
                with open(json_file, "r", encoding="utf-8") as f:
                    data = json.load(f)

                crop_name = data.get("crop", json_file.stem.capitalize())
                diseases = data.get("diseases", {})
                self.crop_records[crop_name.lower()] = data

                for disease_key, record in diseases.items():
                    record["crop"] = crop_name
                    class_name = record.get("class_name", disease_key)
                    self.class_to_record[class_name.lower()] = record
            except Exception as e:
                print(f"Warning: Failed to load treatment file {json_file.name}: {e}")

        # Load disclaimers
        disclaimers_path = self.db_dir / "disclaimers.json"
        if disclaimers_path.exists():
            with open(disclaimers_path, "r", encoding="utf-8") as f:
                self.disclaimers = json.load(f)
        else:
            self.disclaimers = {
                "general_disclaimer": "This advisory is generated by PlantScan AI for preliminary screening. Consult local extension agronomists before field treatments.",
                "chemical_safety_warning": "DANGER/CAUTION: Synthetic chemicals must be applied strictly per label instructions using proper PPE.",
                "uncertainty_notice": "Diagnostic certainty is low. Do not apply broad-spectrum chemical pesticides without physical verification.",
            }

        # Load unknown/unsupported crop defaults
        unknown_path = self.db_dir / "unknown_crop.json"
        if unknown_path.exists():
            with open(unknown_path, "r", encoding="utf-8") as f:
                self.default_unknown = json.load(f)
        else:
            self.default_unknown = {
                "photo_guidance": [
                    "Ensure good natural daylight (avoid direct harsh midday sun or deep shadows).",
                    "Focus sharply on the lesion or affected area.",
                    "Include both top surface and underside of the leaf if possible.",
                    "Avoid taking photos with messy backgrounds or heavy motion blur.",
                ],
                "prevention_measures": [
                    "Isolate plants exhibiting symptoms to avoid cross-contamination.",
                    "Consult your local agricultural university or extension center.",
                ],
                "sources": [
                    "PlantScan AI Knowledge Base",
                    "FAO Integrated Pest Management Guidelines",
                ],
            }

    def list_supported_crops(self) -> List[str]:
        return sorted([data.get("crop", key.capitalize()) for key, data in self.crop_records.items()])

    def list_all_canonical_classes(self) -> List[str]:
        return sorted(list(self.class_to_record.keys()))

    def get_by_class(self, class_name: str) -> Optional[Dict[str, Any]]:
        return self.class_to_record.get(class_name.strip().lower())

    def get_by_crop_and_disease(self, crop: str, disease: str) -> Optional[Dict[str, Any]]:
        record = self.get_by_class(disease)
        if record:
            return record

        crop_clean = crop.strip().lower()
        if crop_clean in self.crop_records:
            diseases = self.crop_records[crop_clean].get("diseases", {})
            d_clean = disease.strip().lower()
            if d_clean in diseases:
                res = diseases[d_clean]
                res["crop"] = self.crop_records[crop_clean].get("crop", crop)
                return res
        return None
